CREATE TABLE IF NOT EXISTS bratko_notes (
    ID int(11) NOT NULL AUTO_INCREMENT,
    AUTHOR_ID int(11) NOT NULL,
    TITLE varchar(255) NOT NULL,
    CONTENT text NULL,
    CREATED_AT datetime NOT NULL,
    UPDATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    INDEX IX_BRATKO_NOTES_AUTHOR (AUTHOR_ID)
);

